# Generated by Django 4.1.3 on 2022-11-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('01', '직거래만'), ('10', '택배거래만'), ('11', '택배/직거래')], max_length=20)),
                ('state', models.CharField(choices=[('WAIT', '대기중'), ('ACCEPT', '수락'), ('LEND', '대여중'), ('TERMINATE', '종료')], default='WAIT', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='_product.product')),
                ('user_cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to=settings.AUTH_USER_MODEL)),
                ('user_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
