# Generated by Django 4.1.3 on 2022-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_deal', '0004_alter_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default="2022-11-07 11:02:05.000000"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('WAIT', '대기중'), ('ACCEPT', '수락'), ('LEND', '대여중'), ('TERMINATE', '종료')], default='WAIT', max_length=20),
        ),
    ]
