# Generated by Django 4.1.3 on 2022-11-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product')),
                ('title', models.CharField(max_length=120)),
                ('area', models.CharField(default='', max_length=100, verbose_name='거래 장소')),
                ('type', models.CharField(choices=[('DIRECT', '직거래만'), ('DELIVERY', '택배거래만'), ('DIRECT/DELEVERY', '택배/직거래')], max_length=20)),
                ('price', models.IntegerField()),
                ('price_per', models.CharField(choices=[('PER_DAY', 'DAY'), ('PER_WEEK', 'WEEK'), ('PER_MONTH', 'MONTH')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('CLOTHES', '의류'), ('SHOES', '신발'), ('TRAVELS', '여행용품'), ('BAGS', '가방'), ('CARRIERS', '캐리어'), ('SPORTS', '스포츠'), ('LEISURES', '레저'), ('HOMES', '가전제품'), ('FURNITURES', '가구'), ('ELECTROMICS', '전자제품'), ('CASUALS', '캐주얼'), ('OTHERS', '기타')], max_length=20)),
                ('memo', models.TextField(default='', max_length=200, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
