# Generated by Django 4.1.3 on 2022-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(1, '직거래만'), (2, '택배거래만'), (3, '택배/직거래')], max_length=20),
        ),
    ]
