# Generated by Django 4.1.3 on 2022-11-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CLOTHES', '의류'), ('SHOES', '신발'), ('TRAVELS', '여행용품'), ('BAGS', '가방'), ('CARRIERS', '캐리어'), ('SPORTS', '스포츠'), ('LEISURES', '레저'), ('HOMES', '가전제품'), ('FURNITURES', '가구'), ('ELECTRONICS', '전자제품'), ('CASUALS', '캐주얼'), ('OTHERS', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(blank=True, default='/media/product/product_dafault.png', null=True, upload_to='product'),
        ),
    ]
