# Generated by Django 4.1.3 on 2022-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0003_alter_product_category_alter_product_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area_detail',
            field=models.CharField(default='', max_length=100, verbose_name='거래 장소'),
        ),
    ]
