# Generated by Django 4.1.3 on 2023-01-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0005_alter_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(blank=True, default='/media/product/product_dafault.png', null=True, upload_to='product'),
        ),
    ]
