# Generated by Django 4.1.3 on 2022-11-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='Representative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='_product.product'),
        ),
    ]
