# Generated by Django 4.1.3 on 2022-11-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0008_alter_product_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='Representative',
        ),
        migrations.AddField(
            model_name='product_image',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
