# Generated by Django 4.1 on 2022-11-15 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/img/product_default.png', null=True, upload_to='chatting')),
                ('text', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to=settings.AUTH_USER_MODEL)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product')),
            ],
        ),
    ]
