# Generated by Django 4.1 on 2022-11-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_chatting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
