# Generated by Django 4.1.3 on 2022-11-03 09:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_search', '0001_initial'),
        ('_product', '0002_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('address', models.TextField()),
                ('phoneNum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('favorite', models.ManyToManyField(related_name='favor', to='_product.product')),
                ('keyword', models.ManyToManyField(related_name='search', to='_search.keyword')),
            ],
        ),
    ]
