# Generated by Django 4.1 on 2022-11-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(max_length=20),
        ),
    ]
