# Generated by Django 4.1.3 on 2022-11-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_search', '0005_curmostsearch_vector'),
        ('_account', '0002_user_favorite_user_view_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyword',
            field=models.ManyToManyField(related_name='search', to='_search.keyword'),
        ),
    ]
