# Generated by Django 4.1 on 2022-11-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0002_alter_user_address_alter_user_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.CharField(max_length=20),
        ),
    ]
