# Generated by Django 4.1.3 on 2022-11-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_search', '0001_initial'),
        ('_product', '0001_initial'),
        ('_account', '0002_user_favorite_user_view_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyword',
            field=models.ManyToManyField(related_name='search', to='_search.keyword'),
        ),
        
    ]
