# Generated by Django 4.1.3 on 2022-11-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0003_user_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_view',
            name='count',
        ),
    ]
