# Generated by Django 4.1.3 on 2022-11-04 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0003_product_created'),
        ('_account', '0004_remove_user_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_view',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product'),
        ),
        migrations.AlterField(
            model_name='user_view',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
