# Generated by Django 4.1.3 on 2022-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0005_alter_user_view_product_alter_user_view_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_save',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
