# Generated by Django 4.1.3 on 2022-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0006_user_search_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/igm/account_default.png', null=True, upload_to='account'),
        ),
    ]
