# Generated by Django 4.1.3 on 2022-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/img/account_default.png', null=True, upload_to='account'),
        ),
    ]
