# Generated by Django 4.1.3 on 2023-01-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0006_alter_product_image_image'),
        ('_search', '0005_curmostsearch_vector'),
        ('_account', '0007_user_address_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(null=True, related_name='favor', to='_product.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='account/account_default.png', null=True, upload_to='account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='keyword',
            field=models.ManyToManyField(null=True, related_name='search', to='_search.keyword'),
        ),
    ]
