# Generated by Django 4.1.3 on 2022-11-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurMostSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_search.keyword')),
            ],
        ),
    ]
