# Generated by Django 4.1.3 on 2022-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_search', '0002_curmostsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curmostsearch',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
