# Generated by Django 4.1.3 on 2022-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_search', '0003_alter_curmostsearch_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='curmostsearch',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default="1991-11-20"),
            preserve_default=False,
        ),
    ]
